sudo: false
cache: bundler
language: ruby
before_install: gem install bundler -v 1.16.1
rvm:
  - 2.3
  - 2.4
  - ruby-head
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
script: bundle exec rake test
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.1
      gemfile: gemfiles/rails32.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails41.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails42.gemfile
